// AUTH TYPES:
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const UNAUTH_USER = 'UNAUTH_USER'

// CART TYPES:
export const ADD_TO_CART = 'ADD_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const GET_CART = 'GET_CART'
export const GET_CART_REJECTED = 'GET_CART_REJECTED'
export const UPDATE_CART = 'UPDATE_CART'
export const UPDATE_CART_REJECTED = 'UPDATE_CART_REJECTED'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const DELETE_CART_ITEM_REJECTED = 'DELETE_CART_ITEM_REJECTED'

// PRODUCT TYPES:
export const POST_PRODUCT = 'POST_PRODUCT'
export const POST_PRODUCT_REJECTED = 'POST_PRODUCT_REJECTED'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_REJECTED = 'GET_PRODUCTS_REJECTED'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED'
export const RESET_BUTTON = 'RESET_BUTTON'
